"""Add attachment fields to email_templates

Revision ID: 13e1d7e40c09
Revises: 37468a996127
Create Date: 2026-03-29 19:48:20.829893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e1d7e40c09'
down_revision = '37468a996127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_path')

    # ### end Alembic commands ###
