"""Add generic processor fields for multi-platform support

Revision ID: 1817e9b8446d
Revises: cff0870d0be1
Create Date: 2026-03-27 13:08:31.647276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1817e9b8446d'
down_revision = 'cff0870d0be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_confirmation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processor_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processor_recurring_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processor_receipt_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('processor_receipt_url')
        batch_op.drop_column('processor_recurring_id')
        batch_op.drop_column('processor_token')
        batch_op.drop_column('processor_confirmation')

    # ### end Alembic commands ###
