"""Add ZTorm tables: agreements, payments, addresses, phones, classifications, memorial_names, communications, donation_events, accounts, collection_batches, credit_cards, standing_orders

Revision ID: 1c3a3c92baf0
Revises: f1c064d88d6d
Create Date: 2026-04-14 10:12:17.010757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3a3c92baf0'
down_revision = 'f1c064d88d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(length=20), nullable=True),
    sa.Column('batch_date', sa.DateTime(), nullable=True),
    sa.Column('charge_date', sa.Date(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('returns_processed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('fixed_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_primary_mail', sa.Boolean(), nullable=True),
    sa.Column('is_invalid', sa.Boolean(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('apartment', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ztorm_hescem_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('agreement_type', sa.String(length=50), nullable=True),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_unlimited', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('certificate_name', sa.String(length=200), nullable=True),
    sa.Column('target_agreement_id', sa.Integer(), nullable=True),
    sa.Column('continuation_agreement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['target_agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agreements_ztorm_hescem_id'), ['ztorm_hescem_id'], unique=False)

    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('is_phone', sa.Boolean(), nullable=True),
    sa.Column('is_fax', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memorial_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_name', sa.String(length=200), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('relationship_to_donor', sa.String(length=50), nullable=True),
    sa.Column('memorial_type', sa.String(length=20), nullable=True),
    sa.Column('hebrew_day', sa.Integer(), nullable=True),
    sa.Column('hebrew_month', sa.Integer(), nullable=True),
    sa.Column('hebrew_year', sa.Integer(), nullable=True),
    sa.Column('kadish_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_agreement_only', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('last_print_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('company_code', sa.Integer(), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('collection_method', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collection_batches.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_recurring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('card_company_code', sa.Integer(), nullable=True),
    sa.Column('clearing_house', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_charges', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('collection_day', sa.Integer(), nullable=True),
    sa.Column('holder_tz', sa.String(length=9), nullable=True),
    sa.Column('is_donor_card', sa.Boolean(), nullable=True),
    sa.Column('has_signature', sa.Boolean(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('limit_to_month', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id')
    )
    op.create_table('standing_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.Integer(), nullable=True),
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_payments', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('collection_day', sa.Integer(), nullable=True),
    sa.Column('period_months', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_manual_split', sa.Boolean(), nullable=True),
    sa.Column('authorization_cancelled', sa.Boolean(), nullable=True),
    sa.Column('received_confirmation', sa.Boolean(), nullable=True),
    sa.Column('confirmation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id')
    )
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('comm_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('executor', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ztorm_tashlum_id', sa.Integer(), nullable=True),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount_nis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usd_equivalent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('authorization_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('check_bank', sa.Integer(), nullable=True),
    sa.Column('check_branch', sa.Integer(), nullable=True),
    sa.Column('check_account', sa.String(length=20), nullable=True),
    sa.Column('check_number', sa.String(length=20), nullable=True),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('credit_status', sa.String(length=20), nullable=True),
    sa.Column('classification_1', sa.String(length=100), nullable=True),
    sa.Column('classification_2', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collection_batches.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_ztorm_tashlum_id'), ['ztorm_tashlum_id'], unique=False)

    op.create_table('accounting_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('sub_type', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ztorm_truma_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agreement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paid_nis', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_usd', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('expected_nis', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('expected_usd', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('entry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('first_payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_paid_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancellation_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('send_receipt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_name_ztorm', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('receipt_tz', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('receipt_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_created', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_donations_ztorm_truma_id'), ['ztorm_truma_id'], unique=False)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ztorm_donor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('spouse_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('spouse_tz', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('send_mail', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mail_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('receipt_tz', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('send_receipts_once', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('send_receipts_yearly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monthly_receipt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_tz_not_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('letter_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('letter_last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('letter_title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('letter_suffix', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classification_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bookmark', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_freq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_donors_ztorm_donor_id'), ['ztorm_donor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donors_ztorm_donor_id'))
        batch_op.drop_column('registration_date')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('follow_up_freq')
        batch_op.drop_column('bookmark')
        batch_op.drop_column('classification_5')
        batch_op.drop_column('classification_4')
        batch_op.drop_column('classification_3')
        batch_op.drop_column('classification_2')
        batch_op.drop_column('classification_1')
        batch_op.drop_column('letter_suffix')
        batch_op.drop_column('letter_title')
        batch_op.drop_column('letter_last_name')
        batch_op.drop_column('letter_first_name')
        batch_op.drop_column('receipt_tz_not_required')
        batch_op.drop_column('monthly_receipt')
        batch_op.drop_column('send_receipts_yearly')
        batch_op.drop_column('send_receipts_once')
        batch_op.drop_column('receipt_tz')
        batch_op.drop_column('receipt_name')
        batch_op.drop_column('mail_reason')
        batch_op.drop_column('send_mail')
        batch_op.drop_column('occupation')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_name')
        batch_op.drop_column('spouse_tz')
        batch_op.drop_column('spouse_name')
        batch_op.drop_column('gender')
        batch_op.drop_column('suffix')
        batch_op.drop_column('title')
        batch_op.drop_column('ztorm_donor_id')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_ztorm_truma_id'))
        batch_op.drop_column('user_created')
        batch_op.drop_column('notes')
        batch_op.drop_column('receipt_email')
        batch_op.drop_column('receipt_tz')
        batch_op.drop_column('receipt_name_ztorm')
        batch_op.drop_column('send_receipt')
        batch_op.drop_column('cancellation_code')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancellation_date')
        batch_op.drop_column('last_paid_date')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('first_payment_date')
        batch_op.drop_column('entry_date')
        batch_op.drop_column('expected_usd')
        batch_op.drop_column('expected_nis')
        batch_op.drop_column('paid_usd')
        batch_op.drop_column('paid_nis')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('department_id')
        batch_op.drop_column('agreement_id')
        batch_op.drop_column('ztorm_truma_id')

    op.drop_table('donation_events')
    op.drop_table('accounting_credits')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_ztorm_tashlum_id'))

    op.drop_table('payments')
    op.drop_table('communications')
    op.drop_table('standing_orders')
    op.drop_table('credit_card_recurring')
    op.drop_table('credit_card_charges')
    op.drop_table('account_allocations')
    op.drop_table('memorial_names')
    op.drop_table('phones')
    op.drop_table('classifications')
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agreements_ztorm_hescem_id'))

    op.drop_table('agreements')
    op.drop_table('addresses')
    op.drop_table('accounts')
    op.drop_table('collection_batches')
    # ### end Alembic commands ###
