"""Add anthropic_api_key to config

Revision ID: 391830d7e565
Revises: c61d093e4d0a
Create Date: 2026-03-27 07:44:17.677652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391830d7e565'
down_revision = 'c61d093e4d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('anthropic_api_key')

    # ### end Alembic commands ###
