"""Add Israeli address fields to donor

Revision ID: 3a3ef1ac4019
Revises: a02da517bff9
Create Date: 2026-04-16 12:33:15.636867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3ef1ac4019'
down_revision = 'a02da517bff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('il_address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('il_address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('il_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('il_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('il_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('il_phone')
        batch_op.drop_column('il_zip')
        batch_op.drop_column('il_city')
        batch_op.drop_column('il_address_line2')
        batch_op.drop_column('il_address_line1')

    # ### end Alembic commands ###
