"""Add donor_comment to donations

Revision ID: 5d536d48b271
Revises: 9c1a3f7094ad
Create Date: 2026-04-14 05:59:46.061118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d536d48b271'
down_revision = '9c1a3f7094ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('donor_comment')

    # ### end Alembic commands ###
