"""Add ActiveTrail email configuration

Revision ID: 5ddb6040c369
Revises: 13e1d7e40c09
Create Date: 2026-03-29 19:57:20.960873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddb6040c369'
down_revision = '13e1d7e40c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activetrail_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activetrail_from_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activetrail_from_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_provider', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('email_provider')
        batch_op.drop_column('activetrail_from_name')
        batch_op.drop_column('activetrail_from_email')
        batch_op.drop_column('activetrail_api_key')

    # ### end Alembic commands ###
