"""add_fax_recipients_table

Revision ID: 67125b0d743f
Revises: 385d0baebd36
Create Date: 2026-05-13 14:22:16.782785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67125b0d743f'
down_revision = '385d0baebd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fax_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bank_number', sa.String(length=10), nullable=False),
    sa.Column('branch_number', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.alter_column('content_b64',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.alter_column('body_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('body_html',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_email_messages_assigned_to_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_to_user_id'], ['id'])

    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weddings_gregorian_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weddings_gregorian_date'), ['gregorian_date'], unique=False)

    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_email_messages_assigned_to_user'), 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('body_html',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('body_text',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('email_attachments', schema=None) as batch_op:
        batch_op.alter_column('content_b64',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    op.drop_table('fax_recipients')
    # ### end Alembic commands ###
