"""Add email SMTP and site URL config

Revision ID: 76373e3a2808
Revises: 783968f3f5c1
Create Date: 2026-02-11 03:38:43.116020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76373e3a2808'
down_revision = '783968f3f5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_host', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_from_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_from_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('email_from_address')
        batch_op.drop_column('email_from_name')
        batch_op.drop_column('smtp_use_tls')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_username')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_host')
        batch_op.drop_column('site_url')

    # ### end Alembic commands ###
