"""Add Stripe publishable keys to config

Revision ID: 783968f3f5c1
Revises: fcc5aa0fd1cd
Create Date: 2026-02-10 15:17:10.564809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '783968f3f5c1'
down_revision = 'fcc5aa0fd1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_test_secret_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_test_publishable_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_live_secret_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_live_publishable_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('stripe_test_key')
        batch_op.drop_column('stripe_live_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_live_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_test_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('stripe_live_publishable_key')
        batch_op.drop_column('stripe_live_secret_key')
        batch_op.drop_column('stripe_test_publishable_key')
        batch_op.drop_column('stripe_test_secret_key')

    # ### end Alembic commands ###
