"""Add processor_type field to payment_processors

Revision ID: 7aeb19924169
Revises: 86be228c3603
Create Date: 2026-03-27 13:42:39.559896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aeb19924169'
down_revision = '86be228c3603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_processors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_processors', schema=None) as batch_op:
        batch_op.drop_column('processor_type')

    # ### end Alembic commands ###
