"""Add cell phone fields for Israeli and foreign

Revision ID: 7b2c24b2be46
Revises: 3a3ef1ac4019
Create Date: 2026-04-16 13:11:47.074365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2c24b2be46'
down_revision = '3a3ef1ac4019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('il_phone_cell', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_cell', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('phone_cell')
        batch_op.drop_column('il_phone_cell')

    # ### end Alembic commands ###
