"""Add DAF donation fields

Revision ID: 86be228c3603
Revises: 1817e9b8446d
Create Date: 2026-03-27 13:41:49.975746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86be228c3603'
down_revision = '1817e9b8446d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_daf_donation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daf_provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_grant_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daf_tracking_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('daf_tracking_id')
        batch_op.drop_column('daf_grant_id')
        batch_op.drop_column('daf_provider')
        batch_op.drop_column('is_daf_donation')

    # ### end Alembic commands ###
