"""Add activetrail group_id and classification

Revision ID: 9c1a3f7094ad
Revises: f5ce78eedac3
Create Date: 2026-03-30 08:12:29.952747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1a3f7094ad'
down_revision = 'f5ce78eedac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activetrail_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activetrail_classification', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('activetrail_classification')
        batch_op.drop_column('activetrail_group_id')

    # ### end Alembic commands ###
