"""Add OpenAI and Google API keys

Revision ID: a02da517bff9
Revises: 1c3a3c92baf0
Create Date: 2026-04-15 11:21:11.462278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a02da517bff9'
down_revision = '1c3a3c92baf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_api_key', sa.Text(), nullable=True))
        batch_op.alter_column('anthropic_api_key',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.alter_column('anthropic_api_key',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.drop_column('google_api_key')
        batch_op.drop_column('openai_api_key')

    # ### end Alembic commands ###
