"""Add mailtrap token field

Revision ID: b9a195a2b72a
Revises: 76373e3a2808
Create Date: 2026-02-11 07:31:28.060712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a195a2b72a'
down_revision = '76373e3a2808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailtrap_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('mailtrap_token')

    # ### end Alembic commands ###
