"""Add teudat_zehut to donors

Revision ID: bf2fd1cf583d
Revises: 5d536d48b271
Create Date: 2026-04-14 06:03:44.309022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2fd1cf583d'
down_revision = '5d536d48b271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teudat_zehut', sa.String(length=9), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('teudat_zehut')

    # ### end Alembic commands ###
