"""Add donor linking and external ID fields

Revision ID: cc68480cca9c
Revises: 7e8c18207271
Create Date: 2026-03-26 05:58:53.389717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc68480cca9c'
down_revision = '7e8c18207271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_donor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_source', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_donors_external_id'), ['external_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_donors_primary_donor_id',
            'donors', ['primary_donor_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donors_primary_donor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_donors_external_id'))
        batch_op.drop_column('external_source')
        batch_op.drop_column('external_id')
        batch_op.drop_column('primary_donor_id')

    # ### end Alembic commands ###
