"""Add multi-processor payment tables

Revision ID: cff0870d0be1
Revises: b70d6fd0f34c
Create Date: 2026-03-27 11:49:06.085050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff0870d0be1'
down_revision = 'b70d6fd0f34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_processors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('supported_currencies', sa.JSON(), nullable=True),
    sa.Column('supported_countries', sa.JSON(), nullable=True),
    sa.Column('supports_recurring', sa.Boolean(), nullable=True),
    sa.Column('supports_refunds', sa.Boolean(), nullable=True),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('fee_fixed_cents', sa.Integer(), nullable=True),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=100), nullable=True),
    sa.Column('organization_country', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('min_amount_cents', sa.Integer(), nullable=True),
    sa.Column('max_amount_cents', sa.Integer(), nullable=True),
    sa.Column('donation_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['payment_processors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_processor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processor_transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processor_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processor_fee_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('processor_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('routing_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('donor_country', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('nedarim_transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nedarim_confirmation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nedarim_keva_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_donations_nedarim_transaction_id', ['nedarim_transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_donations_nedarim_transaction_id', type_='unique')
        batch_op.drop_column('nedarim_keva_id')
        batch_op.drop_column('nedarim_confirmation')
        batch_op.drop_column('nedarim_transaction_id')
        batch_op.drop_column('donor_country')
        batch_op.drop_column('routing_reason')
        batch_op.drop_column('processor_metadata')
        batch_op.drop_column('processor_fee_currency')
        batch_op.drop_column('processor_fee')
        batch_op.drop_column('processor_transaction_id')
        batch_op.drop_column('payment_processor')

    op.drop_table('payment_routing_rules')
    op.drop_table('payment_processors')
    # ### end Alembic commands ###
