"""Add YeshInvoice integration fields

Revision ID: f1c064d88d6d
Revises: bf2fd1cf583d
Create Date: 2026-04-14 06:21:19.344212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c064d88d6d'
down_revision = 'bf2fd1cf583d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yeshinvoice_user_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_secret_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_account_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_default_doc_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yeshinvoice_doc_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_doc_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('yeshinvoice_pdf_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('yeshinvoice_pdf_url')
        batch_op.drop_column('yeshinvoice_doc_number')
        batch_op.drop_column('yeshinvoice_doc_id')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('yeshinvoice_default_doc_type')
        batch_op.drop_column('yeshinvoice_enabled')
        batch_op.drop_column('yeshinvoice_account_id')
        batch_op.drop_column('yeshinvoice_secret_key')
        batch_op.drop_column('yeshinvoice_user_key')

    # ### end Alembic commands ###
