"""Add activetrail_profile_id to config

Revision ID: f5ce78eedac3
Revises: 5ddb6040c369
Create Date: 2026-03-30 07:52:29.017530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ce78eedac3'
down_revision = '5ddb6040c369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activetrail_profile_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('activetrail_profile_id')

    # ### end Alembic commands ###
