"""Initial migration with all models

Revision ID: fcc5aa0fd1cd
Revises: 
Create Date: 2026-02-10 11:57:45.065600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc5aa0fd1cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comm_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('api_secret', sa.String(length=500), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_prefix', sa.String(length=10), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('stripe_test_key', sa.String(length=255), nullable=True),
    sa.Column('stripe_live_key', sa.String(length=255), nullable=True),
    sa.Column('stripe_mode', sa.String(length=10), nullable=True),
    sa.Column('stripe_webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('default_commission_type', sa.String(length=20), nullable=True),
    sa.Column('default_commission_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_language', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('comm_pref_email', sa.Boolean(), nullable=True),
    sa.Column('comm_pref_sms', sa.Boolean(), nullable=True),
    sa.Column('comm_pref_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('language_pref', sa.String(length=5), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('body_template_text', sa.Text(), nullable=True),
    sa.Column('body_template_html', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_prefix', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_prefix', 'fiscal_year', name='uq_org_year')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_temp_password', sa.Boolean(), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_tiers', sa.JSON(), nullable=True),
    sa.Column('language_pref', sa.String(length=5), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aff_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('commission_override_type', sa.String(length=20), nullable=True),
    sa.Column('commission_override_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('goal_amount', sa.Integer(), nullable=True),
    sa.Column('total_raised', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aff_code')
    )
    op.create_table('donation_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('donor_address', sa.String(length=500), nullable=True),
    sa.Column('preset_amount', sa.Integer(), nullable=True),
    sa.Column('preset_type', sa.String(length=20), nullable=True),
    sa.Column('full_url', sa.String(length=1000), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_balance_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('stripe_fee', sa.Integer(), nullable=True),
    sa.Column('stripe_fee_details', sa.JSON(), nullable=True),
    sa.Column('net_amount', sa.Integer(), nullable=True),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True),
    sa.Column('payment_method_brand', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('donation_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_sent', sa.Boolean(), nullable=True),
    sa.Column('receipt_sent_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.Column('fee_refunded', sa.Integer(), nullable=True),
    sa.Column('fee_lost_on_refund', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['link_id'], ['donation_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=False),
    sa.Column('donation_amount', sa.Integer(), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('paid_method', sa.String(length=100), nullable=True),
    sa.Column('paid_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('related_donation_id', sa.Integer(), nullable=True),
    sa.Column('related_link_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['related_link_id'], ['donation_links.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax_id_used', sa.String(length=50), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('email_sent_to', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reissued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('message_queue')
    op.drop_table('commissions')
    op.drop_table('donations')
    op.drop_table('donation_links')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('receipt_counter')
    op.drop_table('message_templates')
    op.drop_table('donors')
    op.drop_table('config')
    op.drop_table('comm_providers')
    # ### end Alembic commands ###
